// get cocktails
export const GET_COCKTAILS_REQUEST = "GET_COCKTAILS_REQUEST";
export const GET_COCKTAILS_SUCCESS = "GET_COCKTAILS_SUCCESS";
export const GET_COCKTAILS_FAILED = "GET_COCKTAILS_FAILED";

// search cocktails
export const SEARCH_COCKTAILS_REQUEST = "SEARCH_COCKTAILS_REQUEST";
export const SEARCH_COCKTAILS_SUCCESS = "SEARCH_COCKTAILS_SUCCESS";
export const SEARCH_COCKTAILS_FAILED = "SEARCH_COCKTAILS_FAILED";

// add/remove items in favorite list
export const ADD_FAVORITE_COCKTAILS_REQUEST = "ADD_FAVORITE_COCKTAILS_REQUEST";
export const REMOVE_FAVORITE_COCKTAILS_REQUEST = "REMOVE_FAVORITE_COCKTAILS_REQUEST";